Refactor HTLC to support HTLT
irisnet/irismod pull request #146
Opened 2021-03-10 02:50 UTC by SegueII

2021-03-16 11:34 UTC, zhangyelong requested changes

2021-03-16 11:34 UTC, zhangyelong commented on modules/coinswap/types/validation.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "invalid input denom, shoule not be begin with (%s)", FormatUniABSPrefix)
```suggestion
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "invalid input denom, should not begin with (%s)", FormatUniABSPrefix)
```

2021-03-16 11:34 UTC, zhangyelong commented on modules/coinswap/types/validation.go
> +		return sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "invalid output denom, shoule not be begin with (%s)", FormatUniABSPrefix)
```suggestion
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "invalid output denom, should not begin with (%s)", FormatUniABSPrefix)
```

2021-03-17 01:53 UTC, chengwenxi commented on modules/htlc/genesis.go
> +			panic(fmt.Sprintf("htlt %s has invalid status %s", htlc.Id, htlc.State.String()))
```suggestion
			panic(fmt.Sprintf("htlt %s has invalid status %s", id, htlc.State.String()))
```

2021-03-17 01:53 UTC, chengwenxi commented on modules/htlc/genesis.go
> +			panic(fmt.Sprintf("htlt %s has invalid status %s", htlc.Id, htlc.State.String()))
this assertion should also for htlc?

2021-03-17 01:53 UTC, chengwenxi commented on modules/htlc/genesis.go
> +			return false
export all htlcs, export all `Open` state htlcs for zero height.

2021-03-17 01:53 UTC, chengwenxi commented on modules/htlc/types/htlc.go
> +	}
```suggestion
	if h.State > Refunded {
		return sdkerrors.Wrapf(ErrInvalidState, "invalid htlc status")
	}
```

2021-03-17 01:53 UTC, chengwenxi commented on modules/htlc/types/htlc.go
> +	if h.Transfer && (h.Direction < 1 || h.Direction > 2) {
ditto.

2021-03-17 06:58 UTC, chengwenxi approved these changes

2021-03-18 06:31 UTC, merged