feat: define erc20 related proto files
irisnet/irismod pull request #387
Opened 2024-04-12 05:32 UTC by dreamer-zq

2024-04-12 10:11 UTC, scott-irisnet requested changes

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/event.proto
> +message EventSwapToERC20 {
add a `string` attribute named `to_contract`

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/event.proto
> +  string contract = 1;
rename `contract` to `from_contract`

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/event.proto
> +  int64 amount = 2;
change the type of `amount` to `cosmos.base.v1beta1.Coin`

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  // SwapFeeToken defines a method for swaping some fee token
.. defines a method for swapping between `IRIS` and `ERIS`

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  // SwapToERC20 defines a method for swaping some erc20 token
.. defines a method for swapping some native token to its ERC20 counterpart

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  // SwapFromERC20 defines a method for some native token
.. defines a method for swapping some ERC20 token to its native counterpart

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  // the native token
.. defines a governance operation for deploying an ERC20 contract that binds to a native token

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  string contract = 1;
remove `contract` as it is redundant

2024-04-12 10:11 UTC, scott-irisnet commented on proto/irismod/token/v1/tx.proto
> +  int64 amount = 2;
change `int64 amount` to `Coin wanted_amount`

2024-04-12 10:41 UTC, mitch1024 commented on contracts/Token.sol
> +        require(msg.sender.code.length == 0, "only called by EOA address");
What does `only called by EOA address` mean? Can't this be called by a 4337 contract?

2024-04-13 02:43 UTC, mitch1024 commented on contracts/Token.sol
> +        require(bytes(to).length > 0, "to must be vaild iaa address");
```suggestion
        require(bytes(to).length > 0, "to must be a vaild iaa address");
```

2024-04-13 14:50 UTC, scott-irisnet approved these changes

2024-04-13 14:53 UTC, merged