Fix minimum deposit calculation
irisnet/irismod pull request #70
Opened 2021-01-12 09:08 UTC by secret2830

2021-01-12 13:51 UTC, chengwenxi commented
it's better to add some unit tests

2021-01-13 02:01 UTC, haifengxi requested changes

2021-01-13 02:15 UTC, SegueII approved these changes

2021-01-13 03:14 UTC, haifengxi requested changes

2021-01-13 03:14 UTC, haifengxi commented on modules/service/keeper/keeper_test.go
> +
Add ibc and ethpeg token denoms in the unit tests, for broader coverage.

2021-01-14 03:22 UTC, haifengxi approved these changes

2021-01-14 03:38 UTC, chengwenxi approved these changes

2021-01-14 03:38 UTC, merged